name: .NET8 Build and Release
on:
  workflow_dispatch:
    inputs:
      kp_tag:
        description: 'Optional tag for kp-protocols-clientsdk'
        required: false
        default: ''

jobs:
  tagging:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
      version: ${{ steps.tag.outputs.version }}
      prerelease: ${{ steps.tag.outputs.prerelease }}
    steps:
      - name: Fetch version tag from kp-protocols-clientsdk
        id: tag
        run: |
          if [ -n "${{ github.event.inputs.kp_tag }}" ]; then
            git clone https://github.com/KodyPay/kp-protocols-clientsdk.git proto-repo
            cd proto-repo
            git checkout tags/${{ github.event.inputs.kp_tag }} -b temp-branch
            version_tag=${{ github.event.inputs.kp_tag }}
          else
            git clone --branch main https://github.com/KodyPay/kp-protocols-clientsdk.git proto-repo
            cd proto-repo
            version_tag=$(git describe --tags --exact-match HEAD 2>/dev/null || echo "")
          fi
          if [[ -z "${version_tag}" ]]; then
            echo "No tag found on the head commit of kp-protocols-clientsdk repo. Failing the action."
            exit 1
          else
            echo "tag=${version_tag}" >> $GITHUB_OUTPUT
            echo "version=${version_tag#v}" >> $GITHUB_OUTPUT
            if [[ "${version_tag}" == *-* ]]; then echo "prerelease=true" >> $GITHUB_OUTPUT; else echo "prerelease=false" >> $GITHUB_OUTPUT; fi
          fi
  tagging-echo:
    needs:
      - tagging
    runs-on: ubuntu-latest
    steps:
      - name: Show tag
        run: |
          echo "Tag: ${{ needs.tagging.outputs.tag }}"

  publish:
    needs:
      - tagging
    permissions:
      packages: write
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Checkout proto repository
        run: |
          git clone https://github.com/KodyPay/kp-protocols-clientsdk.git proto-repo

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          cache: true
          source-url: https://nuget.pkg.github.com/KodyPay/index.json
          cache-dependency-path: dotnet8\packages.lock.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create dotnet package
        run: dotnet pack --configuration Release -p:PackageVersion=${{ needs.tagging.outputs.version }} dotnet8

      - name: Publish to NuGet
        if: ${{ needs.tagging.outputs.prerelease == 'false' }}
        run: dotnet nuget push --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json dotnet8\bin\Release\kody-dotnet8-client.*.nupkg
        # TODO: Sign package

  release:
    needs:
      - publish
      - tagging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          name: ${{ needs.tagging.outputs.tag }}
          tag: ${{ needs.tagging.outputs.tag }}
          body: |
            ${{ github.event.release.body }}
            Package available on https://www.nuget.org/packages/kody-dotnet8-client
          draft: false
          prerelease: ${{ github.ref != 'refs/heads/main' }}
          makeLatest: ${{ github.ref == 'refs/heads/main' }}
