name: .NET8 Build and Release
on:
  repository_dispatch:
    types: [tag-push]
  workflow_dispatch:
    inputs:
      tag:
        description: 'source tag'
        required: true
        type: string

jobs:
  tagging:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}
      version: ${{ steps.set_tag.outputs.version }}
      prerelease: ${{ steps.set_tag.outputs.prerelease }}
    steps:
      - name: Use the tag from the event
        id: set_tag
        run: |
          TAG="${{ inputs.tag || github.event.client_payload.tag }}"
          VERSION=${TAG#v}
          echo "TAG from event: ${TAG}"
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          if [[ "${TAG}" == *-* ]]; then 
            echo "prerelease=true" >> $GITHUB_OUTPUT
          else 
            echo "prerelease=false" >> $GITHUB_OUTPUT
          fi

  tagging-echo:
    needs:
      - tagging
    runs-on: ubuntu-latest
    steps:
      - name: Show tag
        run: |
          echo "Tag: ${{ needs.tagging.outputs.tag }}"

  publish:
    needs:
      - tagging
    permissions:
      packages: write
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Checkout proto repository
        run: |
          git clone https://github.com/KodyPay/kp-protocols-clientsdk.git proto-repo

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          cache: true
          source-url: https://nuget.pkg.github.com/KodyPay/index.json
          cache-dependency-path: dotnet8\packages.lock.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create dotnet package
        run: dotnet pack --configuration Release -p:PackageVersion=${{ needs.tagging.outputs.version }} dotnet8

      - name: Publish to NuGet
        if: ${{ needs.tagging.outputs.prerelease == 'false' }}
        run: dotnet nuget push --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json dotnet8\bin\Release\kody-dotnet8-client.*.nupkg
        # TODO: Sign package

  release:
    needs:
      - publish
      - tagging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          name: ${{ needs.tagging.outputs.tag }}
          tag: ${{ needs.tagging.outputs.tag }}
          body: |
            ${{ github.event.release.body }}
            Package available on https://nuget.pkg.github.com/KodyPay/index.json
          draft: false
          prerelease: ${{ github.ref != 'refs/heads/main' }}
          makeLatest: ${{ github.ref == 'refs/heads/main' }}
